### ISSUE TITLE
Contract page changes

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/blockex#102]
<img width="1463" alt="Снимок экрана 2022-08-22 в 12 27 27" src="https://user-images.githubusercontent.com/94360080/185888231-c6bc3a35-bf51-46a9-b3ff-465c64f779d4.png">

Contract page
Common design view like for Block Page.

Add: 
- line Contract name (Unknown or DAO Core, Voting, BANS, Gallery, Faucet)
- Back button

<img width="1367" alt="Снимок экрана 2022-08-22 в 12 28 01" src="https://user-images.githubusercontent.com/94360080/185888394-1c86d4e2-53f4-4ea6-b7ab-ebd475181224.png">
https://master-net.explorer.beam.mw/contract/d08551e7992f6dffce75c02b923ca95645d5e3ef8b8d18fbc872190c6ac5c9e1

**Comment by dariatarakanova** [comment]
@VikMaevskaya https://www.figma.com/file/xyJpZ0aZ5j1akvLOqjPVU5/beam-blockchain-explorer?node-id=216%3A330
