### ISSUE TITLE
Kernel is not searchable in explorer, whereas it exists in chain

### ISSUE THREAD

**Issue by anatolse** [BeamMW/blockex#11]
1. Kernel with ID ed72eea05bee9a5eac62d32bbfabdd2e84aa99401b7d2baebf6d26c56320b8a9 exists in chain (checked in node.db)

2. I'm able to find it by block height in explorer
https://explorer.beam.mw/block/f5266abef42de16ab77883b38bae1adf7f4afbee0bd65711bd92265c9930a53a
But I cannot find it via direct search

**Comment by Sergei-Beam** [comment]
checked
