### ISSUE TITLE
When Kernel ID is selected in search - it also should be selected in the displayed block (the background should fade in and fade out)

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/blockex#14]

**Comment by alexandrashelenkova** [comment]
Added screen here zpl.io/boDxMGM
The row should be selected with light violet color and faded to normal one after few seconds.

**Comment by Sergei-Beam** [comment]
After search we should move focus  (scrolling-down the page)  to found kernel_id
![search](https://user-images.githubusercontent.com/44496108/53878887-19597380-401e-11e9-92cf-44b237c901ad.gif)

**Comment by Sergei-Beam** [comment]
checked
