### ISSUE TITLE
Graphs for large time resolution should be approximated

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/blockex#15]
We need to approximate Graphs for large time resolution via averaging the data
![image](https://user-images.githubusercontent.com/44496108/53413649-914fea00-39dd-11e9-985b-39dce4e2179b.png)

**Comment by sasha-abramovich** [comment]
there should be a max number of values (for X axis) which should not be exceeded, averages should be calculated for each such value

**Comment by Sergei-Beam** [comment]
checked
