### ISSUE TITLE
Block Explorer - Improve Chart

### ISSUE THREAD

**Issue by gingervik** [BeamMW/blockex#2]
1. Currently not clear what Blocks mean. Is it Block per hour? If so, need to change the title

2. Tooltips on the chart:
   * Date and time have "T" and "Z" letters - need to remove
   * Difficulty has too many decimal digits - 2 or 3 are enough (if at all)

moved from https://github.com/BeamMW/beam/issues/187

**Comment by iscander01** [comment]
Fixed
