### ISSUE TITLE
Transaction Fee chart scale needs to be adjusted

### ISSUE THREAD

**Issue by xempew** [BeamMW/blockex#23]
![Screenshot_20190313-181921_2](https://user-images.githubusercontent.com/31330433/54318426-3c67c280-45de-11e9-8f76-df2219105c14.png)
![Screenshot_20190313-102813_2](https://user-images.githubusercontent.com/31330433/54317800-1a6d4080-45dc-11e9-9831-11491c85b06d.png)
![Screenshot_20190313-102836_2](https://user-images.githubusercontent.com/31330433/54317801-1a6d4080-45dc-11e9-8b55-a15cd2f54f2e.png)

Currently, on the Transaction Fee chart, most block fees appear to look as effectively "0" relative to the largest block fee spikes, despite these supressed values ranging from 100's to 1000's of GROTH. The images above illustrate this.

If the scale could be adjusted for the Transaction Fee chart in some way to handle both the milions of GROTH spikes as well as the 'normal' 100's and 1000's of GROTH fee blocks, the line on the chart would present a greatly more informative and interesting data visualization to look at.

**Comment by sasha-abramovich** [comment]
the Y axis should be logarithmic

**Comment by Sergei-Beam** [comment]
@iscander01 Please make the Y-axis abbreviations are more understandable
![image](https://user-images.githubusercontent.com/44496108/55784524-70d57e00-5ab9-11e9-8de2-4f97b422d866.png)

As an example, make it as it was before
![image](https://user-images.githubusercontent.com/44496108/55784671-b85c0a00-5ab9-11e9-9f9e-d315a91ab1e8.png)

**Comment by Sergei-Beam** [comment]
Currently, the maximum of  Y-axis is 1000M=1Beam
But user can set fee more than 1Beam.
In this case, the Y-axis abbreviations look wrong.
@iscander01The Y-axis abbreviations should grow above than 1000M
![image](https://user-images.githubusercontent.com/44496108/59419412-8a55b780-8dd3-11e9-971c-83b78307a00a.png)

**Comment by Sergei-Beam** [comment]
![image](https://user-images.githubusercontent.com/44496108/103235322-e9960100-4952-11eb-97d9-82098c0536ee.png)
Still reproduced

**Comment by Sergei-Beam** [comment]
checked
