### ISSUE TITLE
The explorer should look good on mobile

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/blockex#24]

**Comment by dariatarakanova** [comment]
https://explorer.beam.mw/

**Comment by dariatarakanova** [comment]
design https://app.zeplin.io/project/5bbb0be5059ca818cf1b0c10/dashboard?seid=5cc31cd94cb7a82cf53991ce

**Comment by gingervik** [comment]
header looks bad on android (xiaomi) default browser and safari
![image](https://user-images.githubusercontent.com/28015224/58790678-879bdb00-85f9-11e9-8f01-aa3ebc9534dd.png)
![image](https://user-images.githubusercontent.com/28015224/58790695-8d91bc00-85f9-11e9-9024-1cd7c8bd0442.png)

**Comment by Sergei-Beam** [comment]
checked
