### ISSUE TITLE
Blocks table - Scaling issue

### ISSUE THREAD

**Issue by gingervik** [BeamMW/blockex#42]
When user has scaling setting like 150% Difficulty column is overlaped with Kernels column
![image](https://user-images.githubusercontent.com/28015224/67203998-34de8680-f415-11e9-9e2e-bf57e17a1414.png)

![image](https://user-images.githubusercontent.com/28015224/67203985-30b26900-f415-11e9-8a46-51d32fb7405e.png)

**Comment by Sergei-Beam** [comment]
General issue was fixed, but the additional issue has appeared: after scrolling to the left, the background is not drawn, reproduced for whole page
![image](https://user-images.githubusercontent.com/44496108/103235651-aa1be480-4953-11eb-909e-ce7a0704b868.png)

**Comment by Sergei-Beam** [comment]
After set scaling settings like 150% -  Charts moved down
![image](https://user-images.githubusercontent.com/44496108/103502522-892b2600-4e62-11eb-9cb1-64c6a67c1ec9.png)

**Comment by Sergei-Beam** [comment]
checked
