### ISSUE TITLE
Create asset explorer pages

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/blockex#55]
Please create assets list on block explorer website

1) Add button "confidential assets" to the right side of search and move "mainnet/testnet" slider to the left https://zpl.io/VYvBR8E
![image](https://user-images.githubusercontent.com/47353570/85027193-4f265b00-b182-11ea-8856-80e2ab4d425d.png)

2) Assets list view  https://zpl.io/29QZy0y
![image](https://user-images.githubusercontent.com/47353570/85027390-8bf25200-b182-11ea-8035-a01a46fc5d6d.png)

3) Asset page https://zpl.io/VOQkDR8
![image](https://user-images.githubusercontent.com/47353570/85027483-a7f5f380-b182-11ea-8e59-32a092463e22.png)

4) Create asset page https://zpl.io/bJmqqKJ (hide optional) 
![image](https://user-images.githubusercontent.com/47353570/85028627-ff489380-b183-11ea-9e29-070c5f1ff3a1.png)

5) Create asset page https://zpl.io/a7A4Jw8 (open optional)

6) Create asset empty page https://zpl.io/VxzY1nx

**Comment by Sergei-Beam** [comment]
checked
