### ISSUE TITLE
Add hash-rate to the difficulty graph in Explorer.

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/blockex#6]
In the difficulty graph, I think we should add hash-rate as well (difficulty divided by 60) - just the units near the difficulty units. It's the same graph.

(suggested by @vcorem)

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova let's design this first. in general we have 2 lines on the same chart that repeat the same values. I think it should be a switch for the same chart, not a separate line or chart.

**Comment by alexandrashelenkova** [comment]
Screens updated 
zpl.io/a8pko1x
zpl.io/bldJw50

**Comment by beam-mw** [comment]
The original intention was to swtich between difficulty and hash rate, otherwise it does not look good in terms of scale. 

This means that all the labels need to switch as well, from Average difficulty to Average hash rate

**Comment by Sergei-Beam** [comment]
@iscander01 new designs added 
Switcher https://zpl.io/a8pko1x
Graph with Hash rate https://zpl.io/2GyypkE

**Comment by Sergei-Beam** [comment]
1. After switching to "Blocks and hash rate" graph the charts legends move 
![image](https://user-images.githubusercontent.com/44496108/53880351-d4374080-4021-11e9-8f99-8dc4c86ec000.png)

2. Change the text
![image](https://user-images.githubusercontent.com/44496108/53878319-9b489d00-401c-11e9-88c5-2f2200274b93.png)
2.1 After switching to "Blocks and hash rate" right "Y" axis should be called "Average hash rate"
2.2 Chart legend "Hashrate" should be called "Average hash rate"

**Comment by Sergei-Beam** [comment]
checked
