### ISSUE TITLE
Explorer - Add design for new info about swap/lelantus

### ISSUE THREAD

**Issue by gingervik** [BeamMW/blockex#60]
As we have new requests for our explorer_api, please, add design for how we should display it
https://github.com/BeamMW/beam/issues/1568

Here is what was added:

Atomic Swaps data:
* Show the entire swaps offers (with CTA - want to swap Beam - download the wallet), paginated or on-scroll list of offers. each offer has: value in beam, value in other currency, other currency type, offer creation time, transaction id on Beam blockchain, approximate offer expiration time
* Total currently active offers (one number)
* total Beam currently offered / total BTC|LTC|etc offered (numbers)

Lelantus (Max Privacy):
* the аverage time to withdraw the coins (a time chart as well)

Other data:
* Exchange rate of BEAM to BTC/USD for every block

**Comment by dariatarakanova** [comment]
Atomic Swap data:
https://zpl.io/2jzWXdO

1) Please add 2 tabs (blocks and atomic swap offer)
2) Add list with AS offers with data
3) Add CTA with link to downloads page on website
![image](https://user-images.githubusercontent.com/47353570/98909045-f5745380-24c9-11eb-806e-7af1599a7a09.png)

4) Add 2 new charts: _Trading volume_ and _Average time to withdraw the max privacy coins_
![image](https://user-images.githubusercontent.com/47353570/98909417-7895a980-24ca-11eb-9340-12ae4c6a708d.png)

5) Add 2 more numbers block: Active swap offers: and Beam transaction volume (last 24h):
![image](https://user-images.githubusercontent.com/47353570/98909465-8b0fe300-24ca-11eb-8622-2c1100df18f5.png)

6) Exchange rate of BEAM to BTC/USD for every block https://zpl.io/aMKkJDJ

**Comment by beam-mw** [comment]
Beam Transaction Wallet plaque should be removed since it is not possible to know it.
Also the plaque list should be moved to the top (or something) because now it will not be possible to see it above the fold on a smaller screen

**Comment by dariatarakanova** [comment]
1) Group plaque and place them at the top the same as here https://zpl.io/bPZJNGA
2) Replace Beams with BEAM. All coins should be in CAPS (GROTH, BTC, LTC, DASH etc.)
3) Please use comma as thousands separator in numbers (e.g 41,393)
4) Please add new filter to Atomic Swap Offers List (Coins:all)

**Comment by Sergei-Beam** [comment]
checked
