### ISSUE TITLE
Add unit "GROTH" to FEE diagram

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/blockex#63]
Please add "GROTH" to Transaction Fee ( Y axis). Should be "Transaction Fee, GROTH"

Current implementation
![image](https://user-images.githubusercontent.com/47353570/102335381-7b3b6100-3f98-11eb-8d4c-50137426ccec.png)

Correct view
![image](https://user-images.githubusercontent.com/47353570/102335411-89897d00-3f98-11eb-888a-fe37e6b9f741.png)

**Comment by Sergei-Beam** [comment]
checked
