### ISSUE TITLE
On MacOS https://beam.mw/downloads/mainnet is opening as page for Windows downloads

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/blockex#65]
I use MacOS. But after click on beam.mw link - downloads for Windows are opening.

change link to https://beam.mw/downloads/mainnet

![image](https://user-images.githubusercontent.com/47353570/102336361-be4a0400-3f99-11eb-9dbd-4696359ca9d5.png)

**Comment by Denis-Asipenko** [comment]
checked
