### ISSUE TITLE
Make bigger paddings between OFFERED VOLUME and AVERAGE TIME TO WITHDRAW charts

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/blockex#66]
Design https://zpl.io/bPZJNGA

Current implementation
![image](https://user-images.githubusercontent.com/47353570/102336643-1ed94100-3f9a-11eb-889d-39d2c714a954.png)

Padding between charts should be bigger than between chart name and chart lines. In current implementation paddings look equals.

![image](https://user-images.githubusercontent.com/47353570/102336951-87282280-3f9a-11eb-8583-e65e71bc5e8c.png)

**Comment by Sergei-Beam** [comment]
Padding was changed to 45 between chart name and chart lines above
