### ISSUE TITLE
Make bigger paddings between lowest charts and another section

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/blockex#67]
Design: https://zpl.io/V1PGYW4

Current implementation
![image](https://user-images.githubusercontent.com/47353570/102337773-95c30980-3f9b-11eb-857e-f2c91f41f205.png)

In design 
![image](https://user-images.githubusercontent.com/47353570/102337884-be4b0380-3f9b-11eb-967d-9301bf03e688.png)

**Comment by Sergei-Beam** [comment]
Padding was increased
