### ISSUE TITLE
Create new chart "Transactions amount"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/blockex#68]
Please create new chart "Transactions amount" that opens from OFFERED VOLUME chart dropdown.
It shows how many regular transactions and shielded transactions were created during previous 24 hours.

https://zpl.io/2GXGOrJ
![image](https://user-images.githubusercontent.com/47353570/102358759-90c08300-3fb8-11eb-8e66-bd5cb72f0137.png)

https://zpl.io/bPZJNGA
![image](https://user-images.githubusercontent.com/47353570/102358737-88684800-3fb8-11eb-9d44-5079fbbdac77.png)

**Comment by Sergei-Beam** [comment]
The new chart was added
