### ISSUE TITLE
Changes in plaque with Atomic Swap info

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/blockex#69]
Hided TOP VOLUMES https://zpl.io/bPZJNGA

![image](https://user-images.githubusercontent.com/47353570/102359178-1e03d780-3fb9-11eb-8023-dce03acced3d.png)

Opened TOP VOLUMES https://zpl.io/V4reePz

![image](https://user-images.githubusercontent.com/47353570/102359500-8bb00380-3fb9-11eb-878f-4c6301126061.png)

1) Rename MOST OFFERED with TOP VOLUMES
2) Add show/hide arrow that will show all coins, or only top 3 coins with the most biggest volume
3) Add USD/BTC switcher to switch currency only for TOP VOLUMES.
4) Remove ACTIVE SWAP OFFERS
![image](https://user-images.githubusercontent.com/47353570/102359649-b9954800-3fb9-11eb-84fc-41992d4bdcc1.png)

**Comment by Sergei-Beam** [comment]
checked
