### ISSUE TITLE
Case when no active swap offers

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/blockex#70]
**Desktop**

1) Please add text "(last 24 hours)" near the title TOTAL OFFERS AMOUNT https://zpl.io/bPZJNGA
![image](https://user-images.githubusercontent.com/47353570/102877690-d2857980-444f-11eb-8c46-c6f014e07683.png)

2) Check the title. it should be "TOP OFFERS"
![image](https://user-images.githubusercontent.com/47353570/102877768-f2b53880-444f-11eb-86ab-21d9ee548026.png)

3) Add text "There are no active offers." when no offers https://zpl.io/2GXGOrJ
![image](https://user-images.githubusercontent.com/47353570/102877835-0bbde980-4450-11eb-853a-fd16396d6bab.png)

4) Display diagram TRANSACTION AMOUNT instead of TOP VOLUMES if no offers. And make text TOP VOLUMES disabled in dropdown list 
![image](https://user-images.githubusercontent.com/47353570/102878039-550e3900-4450-11eb-8dc7-abcc3979b1d7.png)

5) On diagram "TOP VOLUMES" should be info for last 24h as well.
![image](https://user-images.githubusercontent.com/47353570/102878214-969ee400-4450-11eb-990e-51882442b5a4.png)

**Mobile:**

6) Open plaque "TOTAL OFFERS AMOUNT (last 24 hours)" https://zpl.io/agw4D6N
![image](https://user-images.githubusercontent.com/47353570/102878661-4411f780-4451-11eb-853f-511487d176c1.png)

7) Hidden plaque "TOTAL OFFERS AMOUNT (last 24 hours)" https://zpl.io/VkAq8DZ
![image](https://user-images.githubusercontent.com/47353570/102878798-76235980-4451-11eb-87f6-806e4176841a.png)

8) Hidden plaque "TOTAL OFFERS AMOUNT (last 24 hours)" and no active offers https://zpl.io/bWlnr3k
![image](https://user-images.githubusercontent.com/47353570/102878709-5a1fb800-4451-11eb-9cc1-acf0ef49b89d.png)

9) Please Display diagram TRANSACTION AMOUNT instead of TOP VOLUMES if no offers as on desktop

**Comment by Sergei-Beam** [comment]
checked
