### ISSUE TITLE
Icons for coins (DAI, WBTC, ETH, USDT) for explorer

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/blockex#71]
1) Icons for all coins here https://zpl.io/bAekzwe
![image](https://user-images.githubusercontent.com/47353570/104714764-4bfe4800-572e-11eb-85ab-7a01b09d3a1b.png)

2) Please check icons that already added, cuz some of them has border (no need border)
![image](https://user-images.githubusercontent.com/47353570/104714727-3c7eff00-572e-11eb-8835-f241ec58afcc.png)

3) Also I added colors for chart https://zpl.io/bAekzwe
![image](https://user-images.githubusercontent.com/47353570/104715045-a9929480-572e-11eb-805a-cb8f5e1fe5e0.png)

**Comment by Sergei-Beam** [comment]
checked
