### ISSUE TITLE
Have the data from the beginning of blockchain and "forever"

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/blockex#8]
Have a selector to switch the time resolution on chart (1d, 1w, 1 month, 1 year, all time)

**Comment by alexandrashelenkova** [comment]
Screens updated 
zpl.io/a8pko1x
zpl.io/bldJw50

**Comment by Sergei-Beam** [comment]
Checked on https://testnet.explorer.beam.mw/
