### ISSUE TITLE
Add download progress to contract details page

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/blockex#99]
Contract details page is loading is too long, we need a loading progress

https://master-net.explorer.beam.mw/contract/2f4a3a736b10e8a217ff23a8f7fa20959431ab3d1fe3226d044101ee5007e6da

**Comment by dariatarakanova** [comment]
@VikMaevskaya  https://www.figma.com/file/xyJpZ0aZ5j1akvLOqjPVU5/beam-blockchain-explorer?node-id=209%3A52

please have a look

**Comment by VikMaevskaya** [comment]
@dariatarakanova 
for this grey page. it upload slowly. something small without page blocking
https://master-net.explorer.beam.mw/contract/2f4a3a736b10e8a217ff23a8f7fa20959431ab3d1fe3226d044101ee5007e6da

**Comment by VikMaevskaya** [comment]
@dariatarakanova The task changes:
we don't need loader, contract calls will be for 50 calls at one page + pagination (in page style). 


<img width="931" alt="Снимок экрана 2022-08-29 в 14 34 29" src="https://user-images.githubusercontent.com/94360080/187192236-00887083-5203-4e17-a44b-ecfaefb26612.png">

**Comment by dariatarakanova** [comment]
1) Call rows got thinner 
2) In any case for 50 calls - scroll is needed.
3) I propose to fix the bottom paginator, so it will appear when user scroll to "CONTRACT calls" and then fixes at the bottom.
https://www.figma.com/file/xyJpZ0aZ5j1akvLOqjPVU5/beam-blockchain-explorer?node-id=216%3A330

**Comment by VikMaevskaya** [comment]
@dariatarakanova  please, make pagination like in the gallery, with possibility go to the N+2 page in one click
